-- EXEC USP_Trn_Patient_Prescriber 3
Create Procedure USP_TRN_PATIENT_PRESCRIBER (@PatientId INT) As Begin
    Select
        TPP.ID,
        TPP.PATIENT_ID,
        TPP.ISACTIVE,
        TPP.ISDELETED,
        MP.ID As PRESCRIBERID,
        MP.PRESCRIBERNPI,
        MP.PRESCRIBERFIRSTNAME,
        MP.PRESCRIBERLASTNAME,
        MP.PRESCRIBERADDRESS,
        MP.PRESCRIBERCITY,
        MP.PRESCRIBERSTATE,
        MP.PRESCRIBERZIP,
        MP.PRESCRIBERPHONE,
        MP.PRESCRIBERFAX,
        MP.PRESCRIBERFIRSTNAME
        + ' '
        + MP.PRESCRIBERLASTNAME As PRESCRIBERFULLNAME
    From TRN_PATIENT_PRESCRIBER As TPP
    Inner Join MST_PRESCRIBER As MP On TPP.PRESCRIBERID = MP.ID
    Where TPP.PATIENT_ID = @PatientId And ISNULL(TPP.ISDELETED, 0) = 0
End
