-- EXEC USP_UpdateCurrentYearEnrollmentIdsToPatient
CREATE PROCEDURE USP_UPDATECURRENTYEARENROLLMENTIDSTOPATIENT AS BEGIN
    SET NOCOUNT ON;
    UPDATE MST_PATIENT SET PATIENTENROLLMENTID = ISNULL(PE.PATIENT_ENROLL_ID, 0)
    FROM MST_PATIENT AS P
    LEFT JOIN
        TRN_PATIENT_ENROLLMENT AS PE
        ON
            P.PATIENT_ID = PE.PATIENT_ID
            AND (
                PE.PATIENT_ENROLLMENT_STATUS = 0
                OR UPLOADEDYEAR = YEAR(GETDATE())
                OR YEAR(PE.ENROLLMENTDATE) = YEAR(GETDATE())
            )
    WHERE
        P.ACCOUNT_ID IN (
            SELECT ACCOUNT_ID FROM MST_ACCOUNT WHERE ACCOUNTTYPE = 1
        )
    SELECT @@ROWCOUNT AS ROWUPDATECOUNT
END
