-- EXEC USP_GetPracticeDetails 1
Create Procedure USP_GETPRACTICEDETAILS (@PracticeId INT) As Begin Select
    ID,
    PRACTICENAME,
    PRACTICEPHONE,
    PRACTICEADDRESS,
    BILLINGPOCNAME,
    BILLINGPOCEMAIL,
    BILLINGPOCPHONE,
    PRACTICEMANAGERNAME,
    PRACTICEMANAGERPHONE,
    PRACTICEMANAGEREMAIL,
    EHRNAME,
    PRACTICETYPE,
    PRACTICESTATUS,
    ASSIGNEDPROGRAMMANAGER,
    BUSINESSDEVELOPMENTMANAGER,
    BILLINGTYPE,
    BILLINGTIME,
    BILLINGTIMEFEES
From MST_PRACTICE Where ID = @PracticeId End
