-- EXEC USP_CheckPatientActivityAlreadyExist 4,2353,0,81
Create Procedure USP_CHECKPATIENTACTIVITYALREADYEXIST
    (@Activity_ID INT, @Patient_ID INT, @Enroll_ID INT, @InPatientLogID INT)
As Begin
    Select
        PA.PATIENT_ACTIVITY_ID,
        PA.PATIENT_ID,
        PA.ACTIVITY_ID,
        PA.ACTIVITY_TYPE_ID,
        PA.ACTIVITY_START_DATE,
        PA.ACTIVITY_START_TIME,
        PA.ACTIVITY_ACTUAL_START_TIME,
        PA.ACTIVITY_ACTUAL_END_TIME,
        PA.ACTIVITY_ASSIGNED_TO,
        PA.ACTIVITY_NOTE,
        PA.ACTIVITY_START_STATUS,
        PA.ACTIVITY_DELAY_NOTE,
        PA.ACTIVITY_STATUS,
        PA.ACTIVITY_CRETAEDAT,
        PA.ACTIVITY_CREATEDBY,
        PA.ACTIVITY_UPDATEDAT,
        PA.ACTIVITY_UPDATEDBY,
        PA.PATIENT_ENROLL_ID,
        PA.LASTCALLOUTCOME,
        PA.ACTIVITYOUTCOME,
        PA.LASTCALLOUTCOMENAME,
        PA.ACTIVITYOUTCOMENAME,
        PA.ACTIVITYREASONDESCRIPTION,
        PA.ISIMMEDIATEACTIONREQUIRED
    From DBO.TRN_PATIENT_ACTIVITY As PA
    Where
        PA.ACTIVITY_ID = @Activity_ID
        And PA.PATIENT_ID = @Patient_ID
        And (@Enroll_ID = 0 Or PA.PATIENT_ENROLL_ID = @Enroll_ID)
        And (@InPatientLogID = 0 Or PA.INPATIENTLOGID = @InPatientLogID)
        And PA.ACTIVITY_STATUS = 1
    Order By PA.ACTIVITY_START_DATE, PA.PATIENT_ACTIVITY_ID
End
