--exec USP_GetPatientCommunicationDetails 5476
CREATE PROCEDURE USP_GETSIGNATUREATTESTATIONDETAILS
    (@PatientActivityID INT)
AS BEGIN
    SELECT
        P.PATIENT_DOB,
        TPA.PATIENT_ACTIVITY_ID,
        TPA.PATIENT_ID,
        TPA.ACTIVITY_ID,
        TPA.ACTIVITY_START_STATUS,
        TPA.ASSOCIATEDPATIENTACTIVITYIDFORUSER
            AS SELECTEDASSOCIATEDACTIVITIESLIST,
        P.PATIENT_FIRST_NAME + ' ' + P.PATIENT_LAST_NAME AS PATIENTFULLNAME
    FROM TRN_PATIENT_ACTIVITY AS TPA
    INNER JOIN MST_PATIENT AS P ON TPA.PATIENT_ID = P.PATIENT_ID
    WHERE TPA.PATIENT_ACTIVITY_ID = @PatientActivityId
END
