-- EXEC USP_GetMHCallOutcomeReasonList 11
Create Procedure USP_GETMHCALLOUTCOMEREASONLIST (@OutcomeID INT) As Begin Select
    ID,
    OUTCOMEID,
    REASONID,
    REASONTEXT,
    HASTEXTFIELD,
    TEXTFIELDLABLENAME,
    HASREASON
From MSTMHCALLOUTCOMEREASON Where OUTCOMEID = @OutcomeID End
