CREATE PROCEDURE USP_REPORTMINDHEALTHBILLING
    (
        @AccountID INT,
        @fromDate DATETIME,
        @toDate DATETIME,
        @UserID INT = 0,
        @orderBy NVARCHAR(50) = 'PatientFullName',
        @orderDir VARCHAR(4) = 'asc',
        @StartFrom INT = 0,
        @PageSize INT = 999999999
    )
AS BEGIN WITH MINDHEALTHBILLINGREPORTRESULT AS (
    SELECT
        TRA.PATIENT_ACTIVITY_ID,
        TRA.DATEOFSERVICE AS DOS,
        MP.PATIENT_DOB,
        TRA.CPT,
        DXT.DX,
        TRA.ACTIVITY_ASSIGNED_TO,
        MPH.PHYSICIANNAME AS MD,
        FIG.PRIMARYINSURANCE,
        FIG.SECONDARYINSURANCE,
        FIG.TERTIARYINSURANCE,
        FIG.PRIMARYINSURANCEIDNUMBER,
        FIG.SECONDARYINSURANCEIDNUMBER,
        FIG.TERTIARYINSURANCEIDNUMBER,
        MP.PATIENT_FIRST_NAME + ' ' + MP.PATIENT_LAST_NAME AS PATIENTFULLNAME,
        U.USER_FIRST_NAME + ' ' + U.USER_LAST_NAME AS BCMUSERS
    FROM TRN_PATIENT_ACTIVITY AS TRA
    INNER JOIN
        MST_PATIENT AS MP
        ON TRA.PATIENT_ID = MP.PATIENT_ID AND MP.ACCOUNT_ID = @AccountID
    INNER JOIN MST_USER AS U ON TRA.ACTIVITY_ASSIGNED_TO = U.USER_ID
    LEFT JOIN MST_PHYSICIAN AS MPH ON MP.REFERRINGPROVIDERID = MPH.ID
    CROSS APPLY
        FUNCGETDXCODEBYPATIENTACTIVITYID(TRA.PATIENT_ACTIVITY_ID) AS DXT
    CROSS APPLY FUNCGETINSURANCEANDGROUPIDBYPATIENTID(TRA.PATIENT_ID) AS FIG
    WHERE
        TRA.ISSUBMITED = 1
        AND TRA.ISBILLABLE = 1
        AND (@UserID = 0 OR TRA.ACTIVITY_ASSIGNED_TO = @UserID)
        AND DATEOFSERVICE >= @fromDate
        AND DATEOFSERVICE <= @toDate
),

ORDERBYRESULT AS (SELECT
    *,
    ROW_NUMBER() OVER (
        ORDER BY
            CASE WHEN @orderBy = 'DOS' AND @orderDir = 'asc' THEN DOS END,
            CASE WHEN @orderBy = 'DOS' AND @orderDir = 'desc' THEN DOS END DESC
    ) AS ROWNUMBER
FROM MINDHEALTHBILLINGREPORTRESULT)

SELECT
    *,
    (SELECT COUNT(DOS) FROM MINDHEALTHBILLINGREPORTRESULT) AS TOTALROWS
FROM ORDERBYRESULT WHERE ORDERBYRESULT.ROWNUMBER BETWEEN (@StartFrom + 1) AND (@StartFrom + @pageSize) END  --exec USP_ReportMindHealthBilling 22,'31MAR2022','30APR2022',13  --select * from Mst_User
