-- EXEC USP_GetInPatientLogActivityDetails 21069
Create Procedure USP_GETINPATIENTLOGACTIVITYDETAILS
    (@Patient_Activity_ID INT)
As Begin
    Set Nocount On Select
        TPA.PATIENT_ACTIVITY_ID,
        IPL.INPATIENTLOGID,
        IPL.ENROLLMENTSTATUS,
        IPL.ENROLLMENTDATE,
        IPL.ENROLLMENTTYPE,
        TPA.ACTIVITY_ID,
        TPA.ACTIVITY_TYPE_ID,
        TPA.ACTIVITY_START_DATE,
        TPA.ACTIVITY_START_TIME,
        TPA.ACTIVITY_ACTUAL_START_TIME,
        TPA.ACTIVITY_ACTUAL_END_TIME,
        TPA.ACTIVITY_ASSIGNED_TO,
        TPA.ACTIVITY_NOTE,
        TPA.ACTIVITY_DELAY_NOTE,
        TPA.PATIENT_ENROLL_ID,
        TPA.ATTEMPTNUMBER,
        TPA.LASTCALLOUTCOMENAME,
        MA.ACTIVITY_DESCRIPTION,
        MA.ACTIVITYTYPE,
        P.PATIENT_FIRST_NAME,
        P.PATIENT_MIDDLE_NAME,
        P.PATIENT_LAST_NAME,
        P.PATIENT_ID,
        ACTIVITYOUTCOMENAME,
        TPA.ISIMMEDIATEACTIONREQUIRED,
        IPL.RXENROLLMENTDATE,
        MU.USER_FIRST_NAME + ' ' + MU.USER_LAST_NAME As ASSIGNEDTONAME,
        Coalesce(TPA.ACTIVITY_START_STATUS, 1) As ACTIVITY_START_STATUS,
        Coalesce(
            IPL.ENROLLMENTDATE,
            TPA.LASTATTEMPTDATE,
            TPA.ACTIVITY_ACTUAL_END_TIME,
            TPA.ACTIVITY_ACTUAL_START_TIME
        ) As LASTATTEMPTDATE,
        ISNULL(IPL.RXHOMEDELIVERY, 0) As RXHOMEDELIVERY
    From DBO.TRN_PATIENT_ACTIVITY As TPA
    Inner Join
        DBO.MST_PATIENT As P With (Nolock)
        On TPA.PATIENT_ID = P.PATIENT_ID
    Inner Join
        DBO.TRN_INPATIENTLOG As IPL With (Nolock)
        On
            P.PATIENT_ID = IPL.PATIENT_ID
            And TPA.INPATIENTLOGID = IPL.INPATIENTLOGID
    Inner Join DBO.MST_ACTIVITY As MA On TPA.ACTIVITY_ID = MA.ACTIVITY_ID
    Left Join MST_USER As MU On TPA.ACTIVITY_ASSIGNED_TO = MU.USER_ID
    Where TPA.PATIENT_ACTIVITY_ID = @Patient_Activity_ID;
End
