-- EXEC USP_GetPatientActivityDetails 1220
Create Procedure USP_GETPATIENTACTIVITYDETAILS
    (@PatientActivityId INT)
As Begin
    Set Nocount On Select
        MA.ACTIVITY_ID,
        MA.ACTIVITY_NAME,
        MA.ACTIVITYTYPE,
        MA.ACTIVITY_DESCRIPTION,
        TPA.PATIENT_ACTIVITY_ID,
        TPA.PATIENT_ID,
        TPA.ACTIVITY_TYPE_ID,
        MAT.ACTIVITY_TYPE_NAME,
        TPA.ACTIVITY_START_DATE,
        TPA.ACTIVITY_START_TIME,
        TPA.ACTIVITY_ACTUAL_START_TIME,
        TPA.ACTIVITY_ACTUAL_END_TIME,
        TPA.ACTIVITY_ASSIGNED_TO,
        TPA.ACTIVITY_NOTE,
        TPA.ACTIVITY_DELAY_NOTE,
        TPA.ACTIVITY_STATUS,
        TPA.ACTIVITY_CRETAEDAT,
        TPA.ACTIVITY_CREATEDBY,
        TPA.ACTIVITY_UPDATEDAT,
        TPA.ACTIVITY_UPDATEDBY,
        TPA.PATIENT_ENROLL_ID,
        P.PATIENT_FIRST_NAME,
        P.PATIENT_MIDDLE_NAME,
        P.PATIENT_LAST_NAME,
        PAA.ATTEMPTNUMBER As ATTEMPTNUMBER,
        TPA.LASTCALLOUTCOMENAME,
        ACTIVITYOUTCOMENAME,
        TPA.ISIMMEDIATEACTIONREQUIRED,
        (
            Case
                When
                    MU.USER_ID Is Not Null
                    Then MU.USER_FIRST_NAME + ' ' + MU.USER_LAST_NAME
                Else ''
            End
        ) As ACTIVITY_ASSIGNED_TO_NAME,
        Coalesce(TPA.ACTIVITY_START_STATUS, 1) As ACTIVITY_START_STATUS
    From TRN_PATIENT_ACTIVITY As TPA
    Inner Join MST_ACTIVITY As MA On TPA.ACTIVITY_ID = MA.ACTIVITY_ID
    Inner Join MST_PATIENT As P On TPA.PATIENT_ID = P.PATIENT_ID
    Inner Join
        MST_ACTIVITY_TYPE As MAT
        On TPA.ACTIVITY_TYPE_ID = MAT.ACTIVITY_TYPE_ID
    Inner Join
        VIEW_PATIENTACTIVITYATTEMPT As PAA
        On TPA.PATIENT_ACTIVITY_ID = PAA.PATIENT_ACTIVITY_ID
    Left Join
        TRN_ACTIVITY_ATTEMPT As TAA
        On
            TPA.PATIENT_ACTIVITY_ID = TAA.PATIENT_ACTIVITY_ID
            And PAA.ATTEMPTNUMBER = TAA.ATTEMPTNUMBER
    Left Join MST_USER As MU On TPA.ACTIVITY_ASSIGNED_TO = MU.USER_ID
    Where TPA.PATIENT_ACTIVITY_ID = @PatientActivityId
End
