FROM jupyter/base-notebook:python-3.10

ARG APP_HOME=/home/jovyan/notebooks
ARG DATA_DIR=/home/jovyan/data
ARG GX_DIR=/home/jovyan/gx_suites

RUN mkdir $APP_HOME
RUN mkdir $DATA_DIR

COPY ./requirements.txt /${APP_HOME}/requirements.txt 

RUN pip install -r /${APP_HOME}/requirements.txt

COPY ./app.py /${APP_HOME}/app.py
COPY ./helpers.py /${APP_HOME}/helpers.py

WORKDIR ${APP_HOME}

