services:
  ometa:
    image: ometa-satellite
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=development
      - OMETA_DNS=http://host.docker.internal
      - OMETA_TOKEN=${OMETA_DEV_TOKEN}
    ports:
      - "5000:5000"
  